remote:
     user: joshua
     password: port clean cookies clock
     host: joshuacook.me
     dbname: project_6
     port: 5432

remote_dev:
     user: 
     password: 
     host: joshuacook.me
     dbname: project_6_dev
     port: 5432


local: 
     user: 
     password: 
     host: localhost
     dbname: Project6
     port: 5432